### ISSUE TITLE
Query extension csl language recognition and formatting / linting

### ISSUE THREAD

**Issue by asears** [microsoft/AzureMonitorCommunity#17]
Should files containing queries be named with extension .csl rather than .txt? Markdown would be another format providing better ways to format syntax by language.  

csl or kusto extension supports formatting in VSCode
https://marketplace.visualstudio.com/items?itemName=ms-samples.kusto-language

**Comment by rbnmk** [comment]
I think this would be great, also for the extensions in VSCode that are 'looking for' .kql or .csl files.

**Comment by asears** [comment]
Much prefer kql naming than csl, (Kusto) didn't see that as an option.   That was my first intuition for naming these scripts.

The extension description has "Provides syntax-highlighting for Kusto query files (.kusto, .csl) within the Monaco file editor in Azure Repos."

Probably a separate ticket to the extension authors to improve their description, and some updates for various standards sites to reserve the extensions.

**Comment by noakup** [comment]
That's a great suggestion. I'm in touch with Kusto team to get their recommendation, and if they know if plans to suport .kql in VSCode, on the face of it this seems most intuitive.
We've considered markdown (have used it in a previous repo) which really provides nice formatting, but opted for txt for a (somewhat) easier contibuting experience. We're at an early stage and still evaluating.

**Comment by noakup** [comment]
Following Kusto'd recommendation, renamed .txt files to .kql.
