### ISSUE TITLE
Add Azure Synapse/ADW, ADF, Databricks, Security Center

### ISSUE THREAD

**Issue by asears** [microsoft/AzureMonitorCommunity#18]
Add additional examples for following services:

Azure Synapse and Azure Data Warehouse
Azure Data Factory v2 (Resource-Specific Diagnostics)
Security Center Continuous Export
Azure Databricks

**Comment by noakup** [comment]
Thanks! we'll make sure to add these as we have them. We've create a [Top asks page](https://github.com/microsoft/AzureMonitorCommunity/wiki/Top-asks) for contributors (internal and external) to consider.
