### ISSUE TITLE
Clarify this repos purpose and relationship with /microsoft/Application-Insights-Workbooks

### ISSUE THREAD

**Issue by asears** [microsoft/AzureMonitorCommunity#19]
There may be some redundancy with this repo and the workbooks contained within <https://github.com/microsoft/Application-Insights-Workbooks>

Should clarify / contrast purpose & scope, and provide link to other repos provided for Azure Monitor and supporting solutions (Data Explorer Proxy, etc)

**Comment by shijatsu** [comment]
We do not want to create an overlap with Workbooks product github - that is the source of workbook templates that customers/ users have in Azure Portal. This repo is community driven contributions

**Comment by asears** [comment]
Should the readme be updated to reflect this statement and provide a supporting link to the Portal templates?

**Comment by noakup** [comment]
Good idea. added a link to a new [FAQ page](https://github.com/microsoft/AzureMonitorCommunity/wiki/FAQ) that explains this. Thanks for the feedback!
