### ISSUE TITLE
Query process id duration with sequence_detect

### ISSUE THREAD

**Issue by SteffenZeidler** [microsoft/AzureMonitorCommunity#29]
I need a query about the duration of computer processes. After the process has terminated, the system can reuse the Id. With the sequence_detect query sample below the start / exit sequence of the two processes with the reused id 1 is not correct detected. How can I query the correct durations?

```
let Table1 = datatable (Time:datetime, ProcId:int, Action:string)
[
datetime(2020-06-01 8:00), 0, "Start",
datetime(2020-06-01 8:01), 1, "Start",
datetime(2020-06-01 8:02), 1, "Exit",
datetime(2020-06-01 8:03), 2, "Start",
datetime(2020-06-01 8:04), 2, "Exit",
datetime(2020-06-01 8:05), 1, "Start",
datetime(2020-06-01 8:06), 1, "Exit",
datetime(2020-06-01 8:10), 0, "Exit",
];
Table1 | evaluate sequence_detect(Time, 1d, 1d, Start = Action == "Start", Stop = Action == "Exit", ProcId)
```
```
ProcId | Start_Time | Stop_Time | Duration
1 | 2020-06-01T08:01:00Z | 2020-06-01T08:06:00Z | 00:05:00
2 | 2020-06-01T08:03:00Z | 2020-06-01T08:04:00Z | 00:01:00
0 | 2020-06-01T08:00:00Z | 2020-06-01T08:10:00Z | 00:10:00
```

**Comment by noakup** [comment]
Hi @SteffenZeidler ,
I think this operator works differently - it looks for multiple "exits" following the proc's "start" and may find multiple such sequences depending on the max step and max span. For example, this query:
`Table1 
| evaluate sequence_detect(Time, 5m, 1d, Start = (Action == "Start"), Stop = (Action == "Exit"), ProcId)
| sort by ProcId asc`
produces these results:

ProcId  |  Start_Time  |  Stop_time  |  Duration
--|--|--|--
1 | 6/1/2020, 8:01:00.000 AM | 6/1/2020, 8:06:00.000 AM | 00:05:00 |  
1 | 6/1/2020, 8:01:00.000 AM | 6/1/2020, 8:02:00.000 AM | 00:01:00 |  
1 | 6/1/2020, 8:05:00.000 AM | 6/1/2020, 8:06:00.000 AM | 00:01:00 |  
2 | 6/1/2020, 8:03:00.000 AM | 6/1/2020, 8:04:00.000 AM | 00:01:00

I'm not sure yet how to get the output you're looking for, adding that the "wish list". Will try to ask the Kusto team about it as well.

**Comment by noakup** [comment]
Following up on that, I'm glad to say that we have both a workaround and an update that this capability will be supported OOTB in the future. The workaround is using mv-apply and row_cumsum to identify separate sequences for the same process:
datatable(Timestamp:datetime, ProcId:long, Status:string)
[
datetime(2020-06-01 8:00) ,       0,            "Start",
datetime(2020-06-01 8:01) ,       1,            "Start",
datetime(2020-06-01 8:02) ,       1,            "Exit",
datetime(2020-06-01 8:03) ,       2,            "Start",
datetime(2020-06-01 8:04) ,       2,            "Exit",
datetime(2020-06-01 8:05) ,       1,            "Start",
datetime(2020-06-01 8:06) ,       1,            "Exit",
datetime(2020-06-01 8:10) ,       0,            "Exit",
]
| summarize Timestamp=make_list(Timestamp), Status=make_list(Status) by ProcId
| mv-apply Timestamp to typeof(datetime), Status to typeof(string) on 
(
    order by Timestamp asc 
    | extend Proc_Seq_Index=row_cumsum(iif(Status == 'Start', 1, 0))
    | summarize Start_Time=min(Timestamp), End_Time=max(Timestamp) by Proc_Seq_Index
    | extend Duration = End_Time - Start_Time
    | project-away Proc_Seq_Index
)

**Comment by SteffenZeidler** [comment]
Thank you very much for the quick answer.
Here is a possible use of the solution.

```
SecurityEvent
| where EventID in (4688, 4689)
| extend ProcessId = iff(EventID == 4688, NewProcessId, ProcessId)
| summarize TimeGenerated=make_list(TimeGenerated), EventID=make_list(EventID)
  by Computer, Process, ProcessId
| mv-apply TimeGenerated to typeof(datetime), EventID to typeof(int) on
(
order by TimeGenerated asc
| summarize Duration = max(TimeGenerated) - min(TimeGenerated)
  by Proc_Seq_Index=row_cumsum(iif(EventID == 4688, 1, 0))
)
| summarize count(), max(Duration), avg(Duration), make_set(Computer) by Process
```
