### ISSUE TITLE
Add Resource types for AML, Function Apps, Network components to wiki & documentation

### ISSUE THREAD

**Issue by asears** [microsoft/AzureMonitorCommunity#32]
There are likely others available from Azure documentation / region availability & pricing calculator pages which can be monitored via Appinsights / Log Analytics.

Azure Data Lake Analytics
Azure Data Lake Store Gen1
Azure Machine Learning (AML) Workspace
Databricks Workspace
Synapse Analytics Workspace
Function Apps
Public IP Address
VNET
Network Adapter
Network Security Group (NSG)

Sorting the wiki lists alphabetically would also help in terms of identification & maintenance.

**Comment by noakup** [comment]
We've added that to our Top Asks list, and the proper resource types to the Resource Typs list as well.
