### ISSUE TITLE
data collector does not understand data type.

### ISSUE THREAD

**Issue by dhruv-dv** [microsoft/AzureMonitorCommunity#40]
I don't know where I can post this issue so that posting issue here, 

I have write own logger into asp.net to log into log analytics. 
There try to implement distributed tracing with help of activity class which is provided by asp.net core framework, 

Issue is that when we are log TraceId into log as string , it's automatic consider as GUID and append dashes(-). so that we are not able to compare actual TraceId and logged TraceId. 

here problem is Data Collector API does not understand proper data type. 

fea47d6e-5871-c742-a07c-5073e8a7886c  (logged TraceId)
fea47d6e5871c742a07c5073e8a7886c  (original TraceId)

![Data_Collector](https://user-images.githubusercontent.com/15888934/95819959-c93baa80-0d44-11eb-810f-e473fa2be6b1.png)

**Comment by shijatsu** [comment]
Please use Tech forum for such discussion or Yammer  ACP channel https://techcommunity.microsoft.com/t5/azure-monitor/bd-p/AzureMonitor
